doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    types:
      item_id: App\Items\Infrastructure\Persistence\Doctrine\ItemIdType
      order_id: App\Orders\Infrastructure\Persistence\Doctrine\OrderIdType
      order_status: App\Orders\Infrastructure\Persistence\Doctrine\OrderStatusType

    profiling_collect_backtrace: '%kernel.debug%'
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    controller_resolver:
      auto_mapping: true
    mappings:
      Orders:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Orders/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Orders\Domain'
        alias: App\Orders\Domain
      Items:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Items/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Items\Domain'
        alias: App\Items\Domain
      OrderItem:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Orders/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Orders\Domain'
        alias: App\Orders\Domain

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
